// ISO 3166-1 alpha-3 codes for every country name in Intl.DisplayNames('en'),
// matching the flag SVGs shipped by react-flagpack (public/flags/{size}/{code}.svg).
const ISO_ALPHA3_BY_NAME: Record<string, string> = {
  Andorra: 'AND',
  'United Arab Emirates': 'ARE',
  Afghanistan: 'AFG',
  'Antigua & Barbuda': 'ATG',
  Anguilla: 'AIA',
  Albania: 'ALB',
  Armenia: 'ARM',
  Angola: 'AGO',
  Antarctica: 'ATA',
  Argentina: 'ARG',
  'American Samoa': 'ASM',
  Austria: 'AUT',
  Australia: 'AUS',
  Aruba: 'ABW',
  'Åland Islands': 'ALA',
  Azerbaijan: 'AZE',
  'Bosnia & Herzegovina': 'BIH',
  Barbados: 'BRB',
  Bangladesh: 'BGD',
  Belgium: 'BEL',
  'Burkina Faso': 'BFA',
  Bulgaria: 'BGR',
  Bahrain: 'BHR',
  Burundi: 'BDI',
  Benin: 'BEN',
  'St. Barthélemy': 'BLM',
  Bermuda: 'BMU',
  Brunei: 'BRN',
  Bolivia: 'BOL',
  Brazil: 'BRA',
  Bahamas: 'BHS',
  Bhutan: 'BTN',
  'Bouvet Island': 'BVT',
  Botswana: 'BWA',
  Belarus: 'BLR',
  Belize: 'BLZ',
  Canada: 'CAN',
  'Cocos (Keeling) Islands': 'CCK',
  'Congo - Kinshasa': 'COD',
  'Central African Republic': 'CAF',
  'Congo - Brazzaville': 'COG',
  Switzerland: 'CHE',
  'Côte d’Ivoire': 'CIV',
  'Cook Islands': 'COK',
  Chile: 'CHL',
  Cameroon: 'CMR',
  China: 'CHN',
  Colombia: 'COL',
  'Costa Rica': 'CRI',
  Cuba: 'CUB',
  'Cape Verde': 'CPV',
  Curaçao: 'CUW',
  'Christmas Island': 'CXR',
  Cyprus: 'CYP',
  Czechia: 'CZE',
  Germany: 'DEU',
  Djibouti: 'DJI',
  Denmark: 'DNK',
  Dominica: 'DMA',
  'Dominican Republic': 'DOM',
  Algeria: 'DZA',
  Ecuador: 'ECU',
  Estonia: 'EST',
  Egypt: 'EGY',
  'Western Sahara': 'ESH',
  Eritrea: 'ERI',
  Spain: 'ESP',
  Ethiopia: 'ETH',
  Finland: 'FIN',
  Fiji: 'FJI',
  'Falkland Islands': 'FLK',
  Micronesia: 'FSM',
  'Faroe Islands': 'FRO',
  France: 'FRA',
  Gabon: 'GAB',
  Grenada: 'GRD',
  Georgia: 'GEO',
  'French Guiana': 'GUF',
  Guernsey: 'GGY',
  Ghana: 'GHA',
  Gibraltar: 'GIB',
  Greenland: 'GRL',
  Gambia: 'GMB',
  Guinea: 'GIN',
  Guadeloupe: 'GLP',
  'Equatorial Guinea': 'GNQ',
  Greece: 'GRC',
  'South Georgia & South Sandwich Islands': 'SGS',
  Guatemala: 'GTM',
  Guam: 'GUM',
  'Guinea-Bissau': 'GNB',
  Guyana: 'GUY',
  'Hong Kong SAR China': 'HKG',
  'Heard & McDonald Islands': 'HMD',
  Honduras: 'HND',
  Croatia: 'HRV',
  Haiti: 'HTI',
  Hungary: 'HUN',
  Indonesia: 'IDN',
  Ireland: 'IRL',
  Israel: 'ISR',
  'Isle of Man': 'IMN',
  India: 'IND',
  'British Indian Ocean Territory': 'IOT',
  Iraq: 'IRQ',
  Iran: 'IRN',
  Iceland: 'ISL',
  Italy: 'ITA',
  Jersey: 'JEY',
  Jamaica: 'JAM',
  Jordan: 'JOR',
  Japan: 'JPN',
  Kenya: 'KEN',
  Kyrgyzstan: 'KGZ',
  Cambodia: 'KHM',
  Kiribati: 'KIR',
  Comoros: 'COM',
  'St. Kitts & Nevis': 'KNA',
  'North Korea': 'PRK',
  'South Korea': 'KOR',
  Kuwait: 'KWT',
  'Cayman Islands': 'CYM',
  Kazakhstan: 'KAZ',
  Laos: 'LAO',
  Lebanon: 'LBN',
  'St. Lucia': 'LCA',
  Liechtenstein: 'LIE',
  'Sri Lanka': 'LKA',
  Liberia: 'LBR',
  Lesotho: 'LSO',
  Lithuania: 'LTU',
  Luxembourg: 'LUX',
  Latvia: 'LVA',
  Libya: 'LBY',
  Morocco: 'MAR',
  Monaco: 'MCO',
  Moldova: 'MDA',
  Montenegro: 'MNE',
  'St. Martin': 'MAF',
  Madagascar: 'MDG',
  'Marshall Islands': 'MHL',
  'North Macedonia': 'MKD',
  Mali: 'MLI',
  'Myanmar (Burma)': 'MMR',
  Mongolia: 'MNG',
  'Macao SAR China': 'MAC',
  'Northern Mariana Islands': 'MNP',
  Martinique: 'MTQ',
  Mauritania: 'MRT',
  Montserrat: 'MSR',
  Malta: 'MLT',
  Mauritius: 'MUS',
  Maldives: 'MDV',
  Malawi: 'MWI',
  Mexico: 'MEX',
  Malaysia: 'MYS',
  Mozambique: 'MOZ',
  Namibia: 'NAM',
  'New Caledonia': 'NCL',
  Niger: 'NER',
  'Norfolk Island': 'NFK',
  Nigeria: 'NGA',
  Nicaragua: 'NIC',
  Netherlands: 'NLD',
  Norway: 'NOR',
  Nepal: 'NPL',
  Nauru: 'NRU',
  Niue: 'NIU',
  'New Zealand': 'NZL',
  Oman: 'OMN',
  Panama: 'PAN',
  Peru: 'PER',
  'French Polynesia': 'PYF',
  'Papua New Guinea': 'PNG',
  Philippines: 'PHL',
  Pakistan: 'PAK',
  Poland: 'POL',
  'St. Pierre & Miquelon': 'SPM',
  'Pitcairn Islands': 'PCN',
  'Puerto Rico': 'PRI',
  'Palestinian Territories': 'PSE',
  Portugal: 'PRT',
  Palau: 'PLW',
  Paraguay: 'PRY',
  Qatar: 'QAT',
  Réunion: 'REU',
  Romania: 'ROU',
  Serbia: 'SRB',
  Russia: 'RUS',
  Rwanda: 'RWA',
  'Saudi Arabia': 'SAU',
  'Solomon Islands': 'SLB',
  Seychelles: 'SYC',
  Sudan: 'SDN',
  Sweden: 'SWE',
  Singapore: 'SGP',
  'St. Helena': 'SHN',
  Slovenia: 'SVN',
  'Svalbard & Jan Mayen': 'SJM',
  Slovakia: 'SVK',
  'Sierra Leone': 'SLE',
  'San Marino': 'SMR',
  Senegal: 'SEN',
  Somalia: 'SOM',
  Suriname: 'SUR',
  'South Sudan': 'SSD',
  'São Tomé & Príncipe': 'STP',
  'El Salvador': 'SLV',
  'Sint Maarten': 'SXM',
  Syria: 'SYR',
  Eswatini: 'SWZ',
  'Turks & Caicos Islands': 'TCA',
  Chad: 'TCD',
  'French Southern Territories': 'ATF',
  Togo: 'TGO',
  Thailand: 'THA',
  Tajikistan: 'TJK',
  Tokelau: 'TKL',
  'Timor-Leste': 'TLS',
  Turkmenistan: 'TKM',
  Tunisia: 'TUN',
  Tonga: 'TON',
  Türkiye: 'TUR',
  'Trinidad & Tobago': 'TTO',
  Tuvalu: 'TUV',
  Taiwan: 'TWN',
  Tanzania: 'TZA',
  Ukraine: 'UKR',
  Uganda: 'UGA',
  'U.S. Outlying Islands': 'UMI',
  'United States': 'USA',
  Uruguay: 'URY',
  Uzbekistan: 'UZB',
  'Vatican City': 'VAT',
  'St. Vincent & Grenadines': 'VCT',
  Venezuela: 'VEN',
  'British Virgin Islands': 'VGB',
  'U.S. Virgin Islands': 'VIR',
  Vietnam: 'VNM',
  Vanuatu: 'VUT',
  'Wallis & Futuna': 'WLF',
  Samoa: 'WSM',
  Yemen: 'YEM',
  Mayotte: 'MYT',
  'South Africa': 'ZAF',
  Zambia: 'ZMB',
  Zimbabwe: 'ZWE',
  'United Kingdom': 'GBR',
};

// Alternate spellings observed in real-world financial data providers
// (e.g. Yahoo Finance) that don't match the Intl.DisplayNames form above.
const ALIASES: Record<string, string> = {
  'Hong Kong': 'HKG',
  Macau: 'MAC',
  Macao: 'MAC',
  'Czech Republic': 'CZE',
  'Ivory Coast': 'CIV',
  "Cote d'Ivoire": 'CIV',
  Turkey: 'TUR',
  Congo: 'COD',
  'Democratic Republic of the Congo': 'COD',
  'Republic of the Congo': 'COG',
  'Congo, The Democratic Republic Of The': 'COD',
  Vatican: 'VAT',
  'Brunei Darussalam': 'BRN',
  'Falkland Islands (Malvinas)': 'FLK',
  Palestine: 'PSE',
  'Syrian Arab Republic': 'SYR',
  'Virgin Islands (U.S.)': 'VIR',
  'Virgin Islands (British)': 'VGB',
  Myanmar: 'MMR',
  Burma: 'MMR',
  'Slovak Republic': 'SVK',
  'Republic of Korea': 'KOR',
  'Korea, Republic of': 'KOR',
  "Democratic People's Republic Of Korea": 'PRK',
  'Russian Federation': 'RUS',
  'Lao People’s Democratic Republic': 'LAO',
  'Iran, Islamic Republic Of': 'IRN',
  'Bolivia, Plurinational State Of': 'BOL',
  'Venezuela, Bolivarian Republic Of': 'VEN',
  'Tanzania, United Republic Of': 'TZA',
  'Moldova, Republic of': 'MDA',
};

const normalize = (value: string) =>
  value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/&/g, 'and')
    .replace(/\bst\.?\b/gi, 'saint')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();

const CODE_BY_NORMALIZED_NAME = new Map<string, string>(
  Object.entries({ ...ISO_ALPHA3_BY_NAME, ...ALIASES }).map(
    ([name, code]) => [normalize(name), code],
  ),
);

export const getCountryFlagCode = (
  country: string | null | undefined,
): string | undefined => {
  if (!country) {
    return undefined;
  }
  return CODE_BY_NORMALIZED_NAME.get(normalize(country));
};
