/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/screener": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScreener"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/tickers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTickers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/screener/filters/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScreenerFilterOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMarkets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/screener/filters/tickers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScreenerTickerOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSyncStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/sync/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSyncHistoryList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/sync/history/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSyncHistoryDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/sync/history/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelSyncJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncScreener"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/sync/static": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncStatic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/sync/fundamental": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncFundamental"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/sync/compound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncCompound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/sync/technical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncTechnical"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/ticker/{isin}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncSingleTicker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/ticker/{isin}/sync/static": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncSingleTickerStatic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/ticker/{isin}/sync/fundamental": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncSingleTickerFundamental"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/ticker/{isin}/sync/compound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncSingleTickerCompound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/ticker/{isin}/sync/technical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncSingleTickerTechnical"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/ticker/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTicker"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/ticker/{id}/fundamental": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTickerFundamental"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/ticker/{id}/financial-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTickerFinancialHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/ticker/{id}/earnings-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTickerEarningsHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/ticker/{id}/altman-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTickerAltmanHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/ticker/{id}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTickerChart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/ticker/{id}/market-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTickerMarketHours"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/tickers/hidden": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHiddenTickers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/ticker/{id}/unhide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unhideTicker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/tickers/health/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSyncHealthSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/tickers/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSyncHealthList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ticker-source/{source}/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTickerSourceSyncStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ticker-source/yahoo/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncYahoo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ticker-source/xtb/sync/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncXtb"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAll"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlists/membership/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMembership"];
        put: operations["setMembership"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/api/watchlists/{id}/tickers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addTicker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlists/{id}/tickers/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeTicker"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserDto: {
            id: string;
            username: string;
            email: string;
            role: string;
            /** @enum {string} */
            tickerSource: "yahoo" | "xtb";
        };
        PaginationMetaDto: {
            page: number;
            size: number;
            total: number;
            totalPages: number;
        };
        PaginatedUserDto: {
            data: components["schemas"]["UserDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        UpdateUserSettingsDto: {
            /** @enum {string} */
            tickerSource: "yahoo" | "xtb";
        };
        RegisterDto: {
            username: string;
            email: string;
            password: string;
        };
        LoginDto: {
            username: string;
            password: string;
        };
        ResetPasswordDto: {
            email: string;
            token?: string;
            newPassword?: string;
        };
        ResetPasswordResponseDto: {
            token?: string;
            success?: boolean;
        };
        TickerDto: {
            isin: string;
            ticker: string;
            companyName: string;
            sector: string | null;
            industry: string | null;
            marketCap: number | null;
            peRatio: number | null;
            price: number | null;
            country: string | null;
            /** @description Basic description of the company */
            description: string | null;
            employees: number | null;
            /** Format: date-time */
            fiscalYearEnd: string | null;
            /** Format: date-time */
            mostRecentQuarter: string | null;
            /** @description Display name of the market the ticker trades on */
            market: string | null;
            /** @description ISO 4217 currency code the ticker is priced in (e.g. USD, EUR) */
            currency: string | null;
            /** @description Change since the last completed session close, in percent (e.g. 1.23 for +1.23%). While the market is open this compares the last two completed closes; once the market has closed for the day it compares today's close to yesterday's. */
            changePercent: number | null;
            /** @description 5 day change, in percent */
            changePercent5d: number | null;
            /** @description 1 week change, in percent */
            changePercent1w: number | null;
            /** @description 1 month change, in percent */
            changePercent1m: number | null;
            /** @description 3 month change, in percent */
            changePercent3m: number | null;
            /** @description 6 month change, in percent */
            changePercent6m: number | null;
            /** @description Year-to-date change, in percent */
            changePercentYtd: number | null;
            /** @description 1 year change, in percent */
            changePercent1y: number | null;
            /** @description RSI(14) */
            rsi14: number | null;
            /** @description MACD(12,26,9) line */
            macd: number | null;
            /** @description MACD(12,26,9) signal line */
            macdSignal: number | null;
            /** @description MACD(12,26,9) histogram */
            macdHistogram: number | null;
            /** @description Bollinger Band(20,2) upper */
            bbUpper: number | null;
            /** @description Bollinger Band(20,2) middle */
            bbMiddle: number | null;
            /** @description Bollinger Band(20,2) lower */
            bbLower: number | null;
            /** @description Bollinger Band width, in percent */
            bbWidth: number | null;
            /** @description ATR(14) */
            atr14: number | null;
            /** @description 20 day volume ratio (latest volume / 20d avg volume) */
            volumeRatio20d: number | null;
            /**
             * Format: date-time
             * @description When the underlying technical data was last refreshed
             */
            refreshedAt: string | null;
            /** @description Company website URL */
            website: string | null;
            /** @description Company logo image URL */
            logoUrl: string | null;
            psRatio: number | null;
            forwardPE: number | null;
            pegRatio: number | null;
            evToEbitda: number | null;
            evToRevenue: number | null;
            priceToBook: number | null;
            epsTrailing: number | null;
            epsForward: number | null;
            enterpriseValue: number | null;
            fiftyTwoWeekHigh: number | null;
            fiftyTwoWeekLow: number | null;
            /** @description Revenue (TTM) */
            revenue: number | null;
            grossProfit: number | null;
            /** @description Net income (TTM) */
            netIncome: number | null;
            revenuePerShare: number | null;
            ebitda: number | null;
            /** @description In percent */
            grossMargin: number | null;
            /** @description In percent */
            operatingMargin: number | null;
            /** @description In percent */
            ebitdaMargin: number | null;
            /** @description In percent */
            profitMargin: number | null;
            /** @description In percent */
            returnOnEquity: number | null;
            /** @description In percent */
            returnOnAssets: number | null;
            /** @description In percent */
            revenueGrowth: number | null;
            operatingCashflow: number | null;
            /** @description Free cash flow (TTM) */
            freeCashflow: number | null;
            /** @description Capital expenditure (TTM) */
            capex: number | null;
            totalDebt: number | null;
            totalCash: number | null;
            debtToEquity: number | null;
            currentRatio: number | null;
            quickRatio: number | null;
            bookValuePerShare: number | null;
            /** @description In percent */
            dividendYield: number | null;
            /** @description In percent */
            payoutRatio: number | null;
            /** @description In percent */
            fiveYearAvgDividendYield: number | null;
            /** Format: date-time */
            exDividendDate: string | null;
            /** @description e.g. "buy", "hold" */
            analystRating: string | null;
            analystTargetMean: number | null;
            analystTargetLow: number | null;
            analystTargetHigh: number | null;
            analystCount: number | null;
            sharesOutstanding: number | null;
            floatShares: number | null;
            /** @description In percent */
            insidersPercent: number | null;
            /** @description In percent */
            institutionsPercent: number | null;
            /** @description Piotroski F-Score (0-9) */
            piotroskiScore: number | null;
            /** @description Altman Z-Score. > 2.99 safe zone, 1.81-2.99 grey zone, < 1.81 distress zone */
            altmanZScore: number | null;
            sma50: number | null;
            sma200: number | null;
            beta: number | null;
            /** @description 10 day average volume */
            avgVolume10d: number | null;
        };
        PaginatedTickerDto: {
            data: components["schemas"]["TickerDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        ScreenerFilterOptionsDto: {
            sectors: string[];
            industries: string[];
            countries: string[];
            markets: string[];
            currencies: string[];
            analystRatings: string[];
        };
        MarketSummaryDto: {
            /** @description Raw exchange code as used by ticker_static_data.market and sync scheduling (e.g. "NMS", "PAR") */
            market: string;
            /** @description Friendly market_hours label, null if this market has no configured hours yet */
            label: string | null;
            lastCompleteSync: string | null;
        };
        TickerOptionDto: {
            isin: string;
            ticker: string;
            companyName: string;
        };
        PaginatedTickerOptionDto: {
            data: components["schemas"]["TickerOptionDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        SyncStatusDto: {
            /** Format: date-time */
            lastSyncDate: string | null;
        };
        SyncHistoryListItemDto: {
            id: string;
            /** @enum {string} */
            type: "auto" | "manual";
            /** @enum {string} */
            kind: "ticker" | "static" | "fundamental" | "compound" | "technical" | "single_ticker";
            /** @enum {string} */
            status: "running" | "success" | "partial_success" | "failed" | "timeout" | "cancelled";
            /** Format: date-time */
            syncDate: string;
            markets: string[];
            marketLabels: (string | null)[];
            tickerCount: number;
            succeededCount: number;
            failedCount: number;
            triggeredByUserId: string | null;
            triggeredByUsername: string | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt: string | null;
        };
        PaginatedSyncHistoryDto: {
            data: components["schemas"]["SyncHistoryListItemDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        SyncHistoryTickerDto: {
            isin: string;
            ticker: string | null;
            companyName: string | null;
            logoUrl: string | null;
            /** @enum {string} */
            status: "success" | "failed" | "did_not_run";
            error: string | null;
        };
        SyncHistoryDetailDto: {
            id: string;
            /** @enum {string} */
            type: "auto" | "manual";
            /** @enum {string} */
            kind: "ticker" | "static" | "fundamental" | "compound" | "technical" | "single_ticker";
            /** @enum {string} */
            status: "running" | "success" | "partial_success" | "failed" | "timeout" | "cancelled";
            /** Format: date-time */
            syncDate: string;
            markets: string[];
            marketLabels: (string | null)[];
            tickerCount: number;
            succeededCount: number;
            failedCount: number;
            triggeredByUserId: string | null;
            triggeredByUsername: string | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt: string | null;
            tickers: components["schemas"]["SyncHistoryTickerDto"][];
            generalError: string | null;
        };
        FundamentalTickerDto: {
            ticker: string;
            marketCap: number | null;
            peRatio: number | null;
            psRatio: number | null;
            ebitda: number | null;
            totalDebt: number | null;
            totalCash: number | null;
            debtToEquity: number | null;
            enterpriseValue: number | null;
            /** @description Revenue (TTM) */
            revenue: number | null;
            grossProfit: number | null;
            /** @description Net income (TTM) */
            netIncome: number | null;
            revenuePerShare: number | null;
            forwardPE: number | null;
            pegRatio: number | null;
            evToEbitda: number | null;
            evToRevenue: number | null;
            priceToBook: number | null;
            epsTrailing: number | null;
            epsForward: number | null;
            fiftyTwoWeekHigh: number | null;
            fiftyTwoWeekLow: number | null;
            /** @description In percent */
            grossMargin: number | null;
            /** @description In percent */
            operatingMargin: number | null;
            /** @description In percent */
            ebitdaMargin: number | null;
            /** @description In percent */
            profitMargin: number | null;
            /** @description In percent */
            returnOnEquity: number | null;
            /** @description In percent */
            returnOnAssets: number | null;
            /** @description In percent */
            revenueGrowth: number | null;
            /** @description In percent */
            earningsGrowth: number | null;
            operatingCashflow: number | null;
            /** @description Free cash flow (TTM) */
            freeCashflow: number | null;
            /** @description Capital expenditure (TTM) */
            capex: number | null;
            /** @description In percent */
            fcfMargin: number | null;
            /** @description In percent */
            fcfYield: number | null;
            netDebt: number | null;
            netDebtToEbitda: number | null;
            currentRatio: number | null;
            quickRatio: number | null;
            bookValuePerShare: number | null;
            cashPerShare: number | null;
            forwardDividendRate: number | null;
            trailingDividendRate: number | null;
            /** @description In percent */
            dividendYield: number | null;
            /** @description In percent */
            fiveYearAvgDividendYield: number | null;
            /** @description In percent */
            payoutRatio: number | null;
            /** Format: date-time */
            exDividendDate: string | null;
            /** @description e.g. "buy", "hold" */
            analystRating: string | null;
            analystTargetMean: number | null;
            analystTargetLow: number | null;
            analystTargetHigh: number | null;
            analystCount: number | null;
            sharesOutstanding: number | null;
            floatShares: number | null;
            /** @description In percent */
            insidersPercent: number | null;
            /** @description In percent */
            institutionsPercent: number | null;
            /** @description Piotroski F-Score (0-9) */
            piotroskiScore: number | null;
            /** @description Altman Z-Score. > 2.99 safe zone, 1.81-2.99 grey zone, < 1.81 distress zone */
            altmanZScore: number | null;
            sma50: number | null;
            sma200: number | null;
            beta: number | null;
            /** @description S&P 500 52 week change, in percent */
            sp500Change52w: number | null;
            /** @description 30 day average volume */
            avgVolume30d: number | null;
            /** @description 10 day average volume */
            avgVolume10d: number | null;
            /**
             * Format: date-time
             * @description When this fundamental data was last refreshed
             */
            refreshedAt: string | null;
        };
        AnnualFinancialPeriodDto: {
            /** Format: date-time */
            periodEnd: string;
            revenue: number | null;
            ebitda: number | null;
            netIncome: number | null;
            operatingCashflow: number | null;
            capex: number | null;
            freeCashflow: number | null;
            cash: number | null;
            totalDebt: number | null;
            netDebt: number | null;
        };
        FinancialHistoryDto: {
            ticker: string;
            annual: components["schemas"]["AnnualFinancialPeriodDto"][];
        };
        EpsPeriodDto: {
            /** Format: date-time */
            quarter: string;
            actual: number | null;
            estimate: number | null;
        };
        RevenuePeriodDto: {
            /** Format: date-time */
            quarter: string;
            actual: number | null;
        };
        EarningsHistoryDto: {
            ticker: string;
            eps: components["schemas"]["EpsPeriodDto"][];
            revenue: components["schemas"]["RevenuePeriodDto"][];
        };
        AltmanScorePointDto: {
            /** Format: date-time */
            date: string;
            score: number;
        };
        AltmanHistoryDto: {
            ticker: string;
            history: components["schemas"]["AltmanScorePointDto"][];
        };
        CandleDto: {
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            entry: number;
            exit: number;
            low: number;
            high: number;
            volume: number;
        };
        TickerChartDto: {
            ticker: string;
            /** @enum {string} */
            window: "5m" | "1h" | "1d" | "1wk";
            candles: components["schemas"]["CandleDto"][];
        };
        MarketHoursDto: {
            market: string;
            label: string;
            /** @description IANA timezone name, e.g. America/New_York */
            timezone: string;
            /** @description HH:mm, local to timezone */
            preMarketOpen: string | null;
            /** @description HH:mm, local to timezone */
            regularOpen: string;
            /** @description HH:mm, local to timezone */
            regularClose: string;
            /** @description HH:mm, local to timezone */
            postMarketClose: string | null;
        };
        HiddenTickerDto: {
            isin: string;
            ticker: string;
            companyName: string | null;
            logoUrl: string | null;
            errorCount: number;
            lastError: string | null;
            /** Format: date-time */
            lastErrorAt: string | null;
            /** Format: date-time */
            hiddenAt: string | null;
        };
        PaginatedHiddenTickerDto: {
            data: components["schemas"]["HiddenTickerDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        SyncHealthSummaryDto: {
            total: number;
            healthyCount: number;
            unhealthyCount: number;
            healthyPercentage: number;
        };
        TickerSyncHealthDto: {
            isin: string;
            ticker: string;
            companyName: string | null;
            logoUrl: string | null;
            market: string | null;
            marketLabel: string | null;
            /** Format: date-time */
            lastFullSyncedAt: string | null;
            minutesPastClose: number | null;
            /** @enum {string} */
            status: "healthy" | "unhealthy";
            /** @enum {string|null} */
            reason: "never_synced" | "stale_since_close" | null;
        };
        PaginatedTickerSyncHealthDto: {
            data: components["schemas"]["TickerSyncHealthDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        TickerSourceSyncStatusDto: {
            /** @enum {string} */
            source: "yahoo" | "xtb";
            /** Format: date-time */
            lastSyncedAt: string | null;
            /** Format: date-time */
            sourceUpdatedAt: string | null;
            tickerCount: number;
            isSyncing: boolean;
        };
        WatchlistDto: {
            id: string;
            name: string;
            description: string | null;
            tickers: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateWatchlistDto: {
            name: string;
            description?: string;
        };
        WatchlistMembershipDto: {
            watchlistIds: string[];
        };
        SetWatchlistMembershipDto: {
            /** @description Ids of the watchlists the ticker should belong to */
            watchlistIds: string[];
        };
        UpdateWatchlistDto: {
            name?: string;
            description?: string;
        };
        AddWatchlistTickerDto: {
            ticker: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUsers: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserDto"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserSettingsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordResponseDto"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    getScreener: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Column to sort by */
                sortBy?: string;
                sortOrder?: "asc" | "desc";
                /** @description JSON-encoded map of filter key to filter value */
                filters?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTickerDto"];
                };
            };
        };
    };
    getTickers: {
        parameters: {
            query: {
                /** @description Comma-separated list of ticker symbols */
                tickers: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerDto"][];
                };
            };
        };
    };
    getScreenerFilterOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerFilterOptionsDto"];
                };
            };
        };
    };
    getMarkets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketSummaryDto"][];
                };
            };
        };
    };
    getScreenerTickerOptions: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Fuzzy search on ticker or company name */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTickerOptionDto"];
                };
            };
        };
    };
    getSyncStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusDto"];
                };
            };
        };
    };
    getSyncHistoryList: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
                status?: "running" | "success" | "partial_success" | "failed" | "timeout" | "cancelled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSyncHistoryDto"];
                };
            };
        };
    };
    getSyncHistoryDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncHistoryDetailDto"];
                };
            };
        };
    };
    cancelSyncJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncScreener: {
        parameters: {
            query?: {
                /** @description Comma-separated list of markets to scope the sync to; omit to sync every market */
                markets?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncStatic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncFundamental: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncCompound: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncTechnical: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncSingleTicker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncSingleTickerStatic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncSingleTickerFundamental: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncSingleTickerCompound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncSingleTickerTechnical: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTicker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerDto"];
                };
            };
        };
    };
    getTickerFundamental: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundamentalTickerDto"];
                };
            };
        };
    };
    getTickerFinancialHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialHistoryDto"];
                };
            };
        };
    };
    getTickerEarningsHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EarningsHistoryDto"];
                };
            };
        };
    };
    getTickerAltmanHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AltmanHistoryDto"];
                };
            };
        };
    };
    getTickerChart: {
        parameters: {
            query: {
                window: "5m" | "1h" | "1d" | "1wk";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerChartDto"];
                };
            };
        };
    };
    getTickerMarketHours: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketHoursDto"];
                };
            };
        };
    };
    getHiddenTickers: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Fuzzy search on isin or ticker */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedHiddenTickerDto"];
                };
            };
        };
    };
    unhideTicker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSyncHealthSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncHealthSummaryDto"];
                };
            };
        };
    };
    getSyncHealthList: {
        parameters: {
            query: {
                limit?: number;
                page?: number;
                status: "healthy" | "unhealthy";
                /** @description Fuzzy search on isin or ticker */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTickerSyncHealthDto"];
                };
            };
        };
    };
    getTickerSourceSyncStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: "yahoo" | "xtb";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerSourceSyncStatusDto"];
                };
            };
        };
    };
    syncYahoo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncXtb: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistDto"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWatchlistDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistDto"];
                };
            };
        };
    };
    getMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistMembershipDto"];
                };
            };
        };
    };
    setMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetWatchlistMembershipDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistDto"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWatchlistDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistDto"];
                };
            };
        };
    };
    addTicker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWatchlistTickerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistDto"];
                };
            };
        };
    };
    removeTicker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistDto"];
                };
            };
        };
    };
}
