openapi: 3.0.0
paths:
  /:
    get:
      operationId: getData
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - App
  /user:
    get:
      operationId: getUsers
      parameters:
        - name: limit
          required: false
          in: query
          schema:
            minimum: 10
            default: 10
            type: number
        - name: page
          required: false
          in: query
          schema:
            minimum: 1
            default: 1
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserDto'
      tags:
        - User
info:
  title: TraderTavern API
  description: The TraderTavern API documentation
  version: '0.1'
  contact: {}
tags: []
servers: []
components:
  schemas:
    UserDto:
      type: object
      properties:
        id:
          type: number
        username:
          type: string
        email:
          type: string
        role:
          type: string
      required:
        - id
        - username
        - email
        - role
    PaginationMetaDto:
      type: object
      properties:
        page:
          type: number
        size:
          type: number
        total:
          type: number
        totalPages:
          type: number
      required:
        - page
        - size
        - total
        - totalPages
    PaginatedUserDto:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/UserDto'
        meta:
          $ref: '#/components/schemas/PaginationMetaDto'
      required:
        - data
        - meta
